services:
  api:
    build: ./backend/TalkFlow.Api
    ports:
      - '5000:80'
    depends_on:
      - sqlserver
      - redis
  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - api
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 'Your_password123'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sqldata:/var/opt/mssql
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  sqldata:
